# Generated by Django 4.2.20 on 2025-12-26 17:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blog_name', models.CharField(max_length=64)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('background_color', models.CharField(default='#f8f9fa', max_length=7, validators=[
                    django.core.validators.RegexValidator(message='Color must be a valid hex value like #RRGGBB.',
                                                          regex='^#[0-9A-Fa-f]{6}$')])),
                ('card_background_color', models.CharField(default='#ffffff', max_length=7, validators=[
                    django.core.validators.RegexValidator(message='Color must be a valid hex value like #RRGGBB.',
                                                          regex='^#[0-9A-Fa-f]{6}$')])),
                ('card_border_color', models.CharField(default='#e9ecef', max_length=7, validators=[
                    django.core.validators.RegexValidator(message='Color must be a valid hex value like #RRGGBB.',
                                                          regex='^#[0-9A-Fa-f]{6}$')])),
                ('heading_font_family', models.CharField(
                    choices=[('inter', 'Inter'), ('roboto', 'Roboto'), ('georgia', 'Georgia'), ('system', 'System UI'),
                             ('Arial', 'Arial'), ('Courier New', 'Courier New'), ('Verdana', 'Verdana')],
                    default='roboto', max_length=100)),
                ('body_font_family', models.CharField(
                    choices=[('inter', 'Inter'), ('roboto', 'Roboto'), ('georgia', 'Georgia'), ('system', 'System UI'),
                             ('Arial', 'Arial'), ('Courier New', 'Courier New'), ('Verdana', 'Verdana')],
                    default='roboto', max_length=100)),
                ('hero_image_url', models.URLField(blank=True)),
                ('hero_overlay_opacity', models.PositiveSmallIntegerField(default=40,
                                                                          help_text='Overlay opacity percentage from 0 to 60 for better text readability.',
                                                                          validators=[
                                                                              django.core.validators.MinValueValidator(
                                                                                  0),
                                                                              django.core.validators.MaxValueValidator(
                                                                                  60)])),
                ('hero_text_color', models.CharField(default='#ffffff', max_length=7, validators=[
                    django.core.validators.RegexValidator(message='Color must be a valid hex value like #RRGGBB.',
                                                          regex='^#[0-9A-Fa-f]{6}$')])),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
