# Generated by Django 4.2.20 on 2025-05-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('background_color', models.CharField(default='#f8f9fa', max_length=7)),
                ('font_style', models.CharField(default='Segoe UI', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
